ideal_width            = 80
max_width              = 80
reorder_imported_names = true
reorder_imports        = true
report_fixme           = "Always"
wrap_comments          = true
write_mode             = "Overwrite"
